---
abstract: 'OneTool Main module'
author:
  - 'Sebastien Thebert <contact@onetool.pm>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.132830'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: OneTool-Core
requires:
  File::Slurp: '0'
  FindBin: '0'
  JSON: '0'
version: '0.1'
